package org.flink;

import java.util.ArrayList;

import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.flink.processing.jobs.Job;

public abstract class Director {
    protected final StreamExecutionEnvironment streamEnv;
    private final ArrayList<Job> jobs;

    public Director (Integer parallelism) {
        this.jobs = new ArrayList<>();
        this.streamEnv = StreamEnvironment.getEnvInstance();

        this.streamEnv.getConfig().disableAutoGeneratedUIDs();
        this.streamEnv.getConfig().setParallelism(parallelism);

        this.open();
    }

    protected void open () {
    }

    protected final void acceptJob (Job job) {
        this.jobs.add(job);
    }

    public final void start ()
    throws Exception {
        this.jobs.forEach(job -> {
            try {
                job.attachStreamEnv(this.streamEnv);
                job.run();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });

        this.streamEnv.execute();
    }
}
